### PR TITLE
Use common.Hash in VMState

### PR DESCRIPTION
**Pull request by ImTei**
**Description**

Use `common.Hash` type in VMState instead of bytes array. it would improve readability of output files and we don't need to make proof file to get prestate.

Updated:
- We need the same change in the monorepo Asterisc [VMState](https://github.com/ethereum-optimism/optimism/blob/8447d1653a32d2210d8aa2f12c43889de4c3b1c7/op-challenger/game/fault/trace/asterisc/state.go#L21). The PR has been opened in the monorepo: https://github.com/ethereum-optimism/optimism/pull/10967
- This PR temporarily pinned the tip fork as the monorepo version. Once monorepo PR is merged, this PR must updates the monorepo dependency version.
- This PR has some changes to make it compatible with the new monorepo version.
  - To avoid solidity import path issues between `rvsol` and monorepo contracts, I have moved library files in `rvsol/scripts/lib` directory, and changed `forge-std/` to `@forge-std/`.

### CODE REVIEW

**Comment by ajsutton** [comment]
I think we'll need to update `op-challenger` for this as well since it reads that field right?

**Comment by ImTei** [comment]
@ajsutton I naively guessed it works.. but it seems something's broken in the CI. Let me check what should I fix more, including op-challenger.

**Comment by ajsutton** [comment]
My guess is we'll have to change https://github.com/ethereum-optimism/optimism/blob/8447d1653a32d2210d8aa2f12c43889de4c3b1c7/op-challenger/game/fault/trace/asterisc/state.go#L21 to a `common.Hash` as well. Will obviously have to be a separate PR anyway since its a different repo.

**Comment by ImTei** [comment]
@ajsutton right. I'll update it in the monorepo and check via e2e to confirm everything works.

**Comment by ImTei** [comment]
Update: opened a monorepo PR: https://github.com/ethereum-optimism/optimism/pull/10967, and added some details in the PR description.

**Review by pcw109550 — APPROVED** [review]

**Pull request merged**
